import { app, BrowserWindow, Menu, Tray, nativeImage } from 'electron';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { IPC } from '@shared/rpc';
import type { SidecarManager } from './sidecar';

let tray: Tray | null = null;

/**
 * Stark menu bar helper. A compact template-tile glyph adapts to the system
 * menu-bar tint; clicking it shows the command menu spelled out in the spec:
 *   New command / Continue latest / Running jobs / Pending approvals /
 *   Start gateway / Pause agents / Open dashboard / Quit.
 */
export function installTray({
  getMainWindow,
  focusMain,
  sidecar,
}: {
  getMainWindow: () => BrowserWindow | null;
  focusMain: () => void;
  sidecar: SidecarManager;
}): void {
  const icon = makeTemplateIcon();
  tray = new Tray(icon);
  tray.setToolTip('Stark');

  const rebuild = () => {
    const status = sidecar.getStatus();
    const online =
      status.state === 'ready' ? 'online' : status.state === 'starting' ? 'starting' : 'offline';
    const send = (command: string) => {
      focusMain();
      getMainWindow()?.webContents.send(IPC.TrayCommand, command);
    };

    const menu = Menu.buildFromTemplate([
      { label: `Stark · ${online}`, enabled: false },
      { type: 'separator' },
      {
        label: 'New command…',
        accelerator: 'CommandOrControl+Shift+Space',
        click: () => {
          focusMain();
          getMainWindow()?.webContents.send(IPC.PaletteToggle);
        },
      },
      { label: 'Continue latest thread', click: () => send('continue-thread') },
      { type: 'separator' },
      { label: 'Running jobs', click: () => send('running-jobs') },
      { label: 'Pending approvals', click: () => send('approvals') },
      { type: 'separator' },
      { label: 'Start messaging gateway', click: () => send('gateway-start') },
      { label: 'Pause all agents', click: () => send('pause-agents') },
      { type: 'separator' },
      { label: 'Open dashboard', click: focusMain },
      { label: 'Settings…', click: () => send('settings') },
      { type: 'separator' },
      { label: 'Quit Stark', click: () => app.quit() },
    ]);
    tray?.setContextMenu(menu);
  };

  rebuild();
  sidecar.on('status', rebuild);
}

/**
 * Stark silhouette as a macOS menu-bar template image. Looks for the PNGs
 * generated by `npm run icon` and falls back to a tiny inline SVG so the tray
 * always has something to show.
 */
function makeTemplateIcon() {
  const candidates = [
    join(__dirname, '../../resources/tray-icon.png'),
    join(process.resourcesPath ?? '', 'tray-icon.png'),
    join(__dirname, '../../../resources/tray-icon.png'),
  ];
  for (const p of candidates) {
    if (p && existsSync(p)) {
      const img2x = nativeImage.createFromPath(p.replace('.png', '@2x.png'));
      const base = nativeImage.createFromPath(p);
      const img = !img2x.isEmpty() ? img2x : base;
      img.setTemplateImage(true);
      return img;
    }
  }
  // Fallback compass-star
  const svg = `<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><polygon points="8 0.5, 9.5 6.5, 15.5 8, 9.5 9.5, 8 15.5, 6.5 9.5, 0.5 8, 6.5 6.5" fill="black"/></svg>`;
  const img = nativeImage.createFromBuffer(Buffer.from(svg));
  img.setTemplateImage(true);
  return img;
}
